### PR TITLE
Changed dependency on 3.2.1 which had a serious security issue (court…

### PR DESCRIPTION
**Pull request by st326**
…esy Google Operation Rosehub)

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by st326** [comment]
For reference, this is a fix for the following issue:

https://commons.apache.org/proper/commons-collections/security-reports.html

http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

I'm one of a number of volunteers at Google who are submitting patches for
approx. 3000 open source applications that had the dependency on 3.2.1.

On Tue, Mar 8, 2016 at 8:49 AM, Paweł Gesek notifications@github.com
wrote:

> test this please
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/motech/modules/pull/198#issuecomment-193859656.

## 

Sarah Thompson, Staff SWE, Security & Privacy
US-MTV-1225 2S0E,  Google Voice: +1 (415) 736-7781, Cell: +1 (650) 713-7463

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
@st326 thanks for your contribution

**Pull request merged**
