### PR TITLE
MOTECH-2149 Attempt to fix failing EventHandlerBundleIT in DHIS

### PR DESCRIPTION
**Pull request by sebbrudzinski**
- A wait condition has been added to the test, to start the test execution, only after the event Inbound channel has started

### CODE REVIEW

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
test this psql

**Comment by pgesek** [comment]
test this psql

**Comment by sebbrudzinski** [comment]
test this please

**Comment by sebbrudzinski** [comment]
test this psql

**Comment by sebbrudzinski** [comment]
test this psql

**Comment by sebbrudzinski** [comment]
test this psql

**Pull request merged**
