### PR TITLE
MOTECH-2911 Create Reports Tab in CommCare UI

### PR DESCRIPTION
**Pull request by srujan92**
1. Created a Report Tab
2. Appended the UI to display list columns(collapsable) and filters of each report with both JSON and tabular view.
3. Adjusted the CSS properties and added js controller functionality and angular service for calling report controller from back-end point.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by srujan92** [comment]
@kmadej This part of code displays static reports data just to show the reviewer how the display looks, the service call code block in controller.js is commented, when the back-end controller is done, the commented code can be un-commented and the static reports data can be removed.

**Comment by kmadej** [comment]
Ok, @mkruszynski will handle this

**Comment by mkruszynski** [comment]
@kmadej @srujan92 I have finished this issue. Results are in #507

**Pull request closed without merging**
