### PR TITLE
MOTECH-2726 Cherry-pick - changing Commcare task actions from event to service method type

### PR DESCRIPTION
**Pull request by filgomul**
It's cherry-pick of commits from #344

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by martokarski** [comment]
test this please

**Pull request merged**
