### PR TITLE
MOTECH-2228: fix retreving data in dhis2 release 2.22

### PR DESCRIPTION
**Pull request by matkwiatkowski**
- there was a change in retrieve list of objects in DHIS 2.22 release, now server replies only with id and display name instead of full data object, especially there was lack of href attribute so it was impossible to retrieve detailed information about object in list; to get full object information while getting list of them api requires to add "?fields=:identifiable" filter at the end of URL, another solution is to get information for every single object
- also fixed typo in DHIS2 contollers.js, that causes error in browser console and empty table of Tracked Entities

for checking api changes view [2.22](https://www.dhis2.org/222-upgrade)

### CODE REVIEW

**Comment by pgesek** [comment]
@PiotrZurawskiSolDevelo please checks this with the different dhis viersions

**Comment by PiotrZurawskiSolDevelo** [comment]
@pgesek @mkwiatkowskisoldevelo  i checked this.
I have possibility to Sync the DHIS2 MOTECH module with the DHIS2 application in version 2.20(older version), 2.22, 2.23 and 2.24.
Sync is working correctly but I can not see statement about successfully Synced application.

**Comment by matkwiatkowski** [comment]
@PiotrZurawskiSolDevelo now sync message displays on UI. Please verify this.

**Comment by PiotrZurawskiSolDevelo** [comment]
I checked this and now everything is working correctly.

**Pull request merged**
