### PR TITLE
Revert "MOTECH-3080: Fixed observations group"

### PR DESCRIPTION
**Pull request by mkruszynski**
Reverts motech/modules#511

### CODE REVIEW

**Comment by kmadej** [comment]
please verify the feature after revert. Remember to update rest module version, more info on JIRA

**Comment by kkedys** [comment]
The same problem still exists. 

1. Observation with ANC Concept, without obs value and with the following children (obs groupsMembers)
a) Observation with Visit Month Concept, obs value = 3
b) Observation with ANC Visit Concept, obs value = 2nd
c) Observation with Diagnosis Concept, without obs value, with the following children (obs groupsMembers)
Observation with High Risk Concept, obs value = No

The problem that I reached concerns the situation "c" (Observation with Diagnosis Concept, without obs value, with the following children (obs groupsMembers). This observation is independent, its GroupMember should be the observation "1" (Observation with ANC Concept, without obs value and with the following children (obs groupsMembers)) ans it's not.

**Comment by mkruszynski** [comment]
@kkedys I checked this once again. Everything is working well. Have you the latest changes? Independent observations was occurring before revert of my changes.
Can you check this again?

**Comment by kkedys** [comment]
During the configuration/installation, I have made a mistake. Now, all observations are visible.@kmadej, the issue is fixed.

**Pull request merged**
