### PR TITLE
MOTECH-1926: Clean up duplicating datepicker code

### PR DESCRIPTION
**Pull request by atish160384**
Cleared duplicate datepicker code from commcare module

### CODE REVIEW

**Comment by kmadej** [comment]
You have just moved this datePickers to motech repo. It's not the best solution, try to clean up duplicating code and reuse datePicker with a little modifications if needed.

**Comment by llavoie** [comment]
Hi @atish160384 do you plan to rework this solution and resubmit?

**Comment by atish160384** [comment]
There are no other datepickers in modules repository. I think this is it.

**Comment by pgesek** [comment]
What is the status of this pull request? Should we close it or get it through the CI?

**Comment by pgesek** [comment]
@atish160384 just looking at this now and sure what is the point of this - weren't we supposed to use the platform datepickers instead of custom definitions, like these ones in Commcare?

**Comment by shanmukhm** [comment]
I'll rework on this and try to come up with a better solution

**Comment by pgesek** [comment]
@shanmukhm fine, I'm closing this for now

**Pull request closed without merging**
