### PR TITLE
MOTECH-2606: Disabled save button until configuration is verified

### PR DESCRIPTION
**Pull request by MichalKus**
Saved button is disabled when configuration is not verified and we turn it on after successful verification

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
test this please

**Comment by jredlarski** [comment]
@kmadej Looks good to me

**Pull request merged**
