### PR TITLE
MOTECH-1967:show message when configuration is saved

### PR DESCRIPTION
**Pull request by matkwiatkowski**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by sebbrudzinski** [comment]
Please push the commit with the fixes to the branch, from which you have created the pull request. It will get updated automatically. I'm closing this one.

**Pull request closed without merging**
