### PR TITLE
MOTECH-2338 Deleted metrics module, renamed motech-metrics to metrics

### PR DESCRIPTION
**Pull request by weronika-redlarska**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by pgesek** [comment]
Conflicts need resolution

**Comment by sebbrudzinski** [comment]
test this please

**Pull request merged**
