### PR TITLE
MOTECH-2654 Add Task Triggers for Actions Involving Contacts

### PR DESCRIPTION
**Pull request by ScottKimball**
This is the final pull request for the RapidPro module. This PR should satisfy the following:

MOTECH-2654 Add Task Triggers for Actions Involving Contacts
MOTECH-2914 Document the RapidPro module
MOTECH-2436 Rapid Pro Module > Expose user configuration in the UI

The completion of these should satisfy the epic:
MOTECH-2067 Integrate MOTECH with RapidPro

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by ScottKimball** [comment]
@pgesek @kmadej This is ready for review.

**Comment by ScottKimball** [comment]
There appears to be a test failure in the care services directory module. I'm not sure what that's about.

**Pull request merged**
