### PR TITLE
MOTECH-2838 Cherry pick - OpenMRS added Get CohortQuery Report Task action

### PR DESCRIPTION
**Pull request by filgomul**
Cherry pick of changes made in #383

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kmadej** [comment]
test this please

**Pull request merged**
