### PR TITLE
MOTECH-1732: Removes doInTransaction methods in IT tests

### PR DESCRIPTION
**Pull request by kmadej**
After my changes on main repo (https://github.com/motech/motech/pull/32), we can remove some transactions from IT tests.
Also I fixed bug in CMS Lite and added some new transactions in
schedule-tracking.

### CODE REVIEW

**Comment by kmadej** [comment]
test this please

**Comment by sebbrudzinski** [comment]
test this please

**Comment by kmadej** [comment]
test this please

**Comment by kmadej** [comment]
test this please

**Pull request merged**
