### PR TITLE
MOTECH-2209 Documenting the CSD module and...

### PR DESCRIPTION
**Pull request by craigappl**
added the following updates to the module documentation:
- Updated the copyright date to 2016
- Rearranged the index to be in order

### CODE REVIEW

**Comment by craigappl** [comment]
FYI @llavoie 

I had to cancel my other pull request and created this one.

**Comment by craigappl** [comment]
test this please

**Comment by craigappl** [comment]
@llavoie Can you have another look at this quickly?

**Comment by llavoie** [comment]
Apologies for the delay -- looks good

**Pull request merged**
