### PR TITLE
Standarized REST Endpoints related to pagination

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by pgesek** [comment]
test this please

**Comment by sebbrudzinski** [comment]
test this please

**Comment by ngraczewski** [comment]
Sorting on the UI is broken

**Comment by sebbrudzinski** [comment]
@ngraczewski Can you verify this is the only remaining place where we need this adjustment?

**Comment by sebbrudzinski** [comment]
test this please

**Comment by ngraczewski** [comment]
@sebbrudzinski I couldn't find any other module that need standardization.

**Pull request merged**
