### PR TITLE
MOTECH-2799 Program enrollment attributes to task create action - Cherry pick

### PR DESCRIPTION
**Pull request by filgomul**
Cherry-pick of changes made in #374

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by kmadej** [comment]
test this please

**Pull request merged**
