### PR TITLE
MOTECH-2726 Unit tests for commcare task actions services (#344)

### PR DESCRIPTION
**Pull request by filgomul**
Unit tests to services added in pull request #344

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by filgomul** [comment]
I updated the tests to keep up with my other changer in #344

**Comment by martokarski** [comment]
test this please

**Pull request merged**
